sonar.projectKey=VidiomTM_runner-infra
sonar.organization=vidiomtm
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,**/__pycache__/**,**/*.bak,**/.git/**,**/target/**
sonar.cpd.exclusions=node_modules/**,**/__pycache__/**,**/*.bak
sonar.autoscan.enabled=false
